	PROGRAM MAIN
	
      PARAMETER (MAXN=10)
      INTEGER N,I
	REAL VX(MAXN),VY(MAXN),VR(MAXN)
	
      WRITE(*,*)'DIGITA IL NUMERO DI COMPONENTI DEI VETTORI'
	READ(*,*)N

	DO I=1,N
	 WRITE(*,*)'INSERISCI I VALORI DI VX(',I,')'
	 READ(*,*)VX(I)
	END DO
	
      WRITE(*,*)'INSERISCI I VALORI DI VY'
	READ(*,*)(VY(I),I=1,N)

      CALL SUB_SOMMA_VETTORI (N,VX,VY,VR)
	WRITE(*,*)(VR(I),I=1,N)
	
      END