	PROGRAM SOMMA_MATRICI

DICHIARAZIONE DELLE VARIABILI
	PARAMETER (MAX=10)
PARAMETER DICHIARA UNA COSTANTE, ASSEGNATA IN FASE DI COMPILAZIONE
	INTEGER M,N,I,J
	REAL A(MAX,MAX),B(MAX,MAX),R(MAX,MAX)

INPUT DIMENSIONI MATRICI
	WRITE(*,*)'Che dimensioni hanno le matrici?'
	READ(*,*) M,N

INPUT MATRICE A
	WRITE(*,*)'Inserisci gli elementi della matrice A'
	READ(*,*)((A(I,J),J=1,N),I=1,M)

INPUT MATRICE B	
      WRITE(*,*)'Inserisci gli elementi della matrice B'
	READ(*,*)((B(I,J),J=1,N),I=1,M)

CHIAMATA SUBROUTINE
	CALL SUM_MAT(M,N,A,B,R,MAX)

OUTPUT MATRICE SOMMMA
      WRITE(*,*)((R(I,J),J=1,N),I=1,M)

	END