 	SUBROUTINE SUM_MAT(M,N,A,B,R,MAX)

DICHIARAZIONE VARIABILI
      INTEGER M,N,I,J
      REAL A(MAX,N),B(MAX,N),R(MAX,N)

CICLO DI SOMMA	
	DO I=1,M
	 DO J=1,N
	  R(I,J)=A(I,J)+B(I,J)
	 END DO
	END DO
		
      END