      PROGRAM MAIN
INIZIALIZZAZIONE VARIABILI DI ESEMPIO
	REAL X(10),A(2,2),B(20),C(3,10),D(10,3),S1,S2,S3,S4,S5,S6,S7
CHIAMATA SUBROUTINE DI SOMMA CON DIVERSE COMBINAZIONI DI VARIABILI
	CALL SUB_SOMMA(X,B,S1)
	CALL SUB_SOMMA(A,C,S2)
	CALL SUB_SOMMA(B,B(8),S3)
	CALL SUB_SOMMA(C,D(2,1),S4)
	CALL SUB_SOMMA(X,C(3,4),S5)
	CALL SUB_SOMMA(B,X,S6)
	CALL SUB_SOMMA(D(7,7),B(10),S7)
	END