	PROGRAM MAIN

	INTEGER N
	N=1

	DO WHILE(N.NE.0)
	 WRITE(*,*)'INSERISCI UN NUMERO INTERO PER VALUTARE SE E'' PARI O D
     -ISPARI'
       WRITE(*,*)'INSERISCI 0 PER USCIRE'
	 READ(*,*)N

	 CALL EVENODD(N)
	
      END DO
	
      END